apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: nginx-deploy
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-deploy
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50